AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure for Cloud Resume Challenge

Parameters:
  BucketName:
    Type: String
    Description: "Name of the S3 bucket for website hosting"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
